/* Pigskin Poker - shared helpers for the local-development scripts.
 *
 * `.env.local` is generated by `npm run dev` from what the local Supabase stack
 * actually reports, rather than copied by hand out of `supabase status`. The copy step
 * was the single most common way to end up with a dev server pointed at nothing, and it
 * is exactly the kind of manual step that gets skipped.
 *
 * Nothing here is used by the app or the server - these are development scripts only.
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { isLocalUrl } from "../server/localUrl.js";

export const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
export const ENV_PATH = path.join(ROOT, ".env.local");

/** The keys `npm run dev` owns. Anything else in .env.local is preserved untouched. */
export const MANAGED_KEYS = [
  "VITE_SUPABASE_URL",
  "SUPABASE_URL",
  "VITE_SUPABASE_PUBLISHABLE_KEY",
  "SUPABASE_SECRET_KEY",
];

/** Parse `KEY=value` / `KEY="value"` lines. Blank lines and `#` comments are ignored. */
export function parseEnv(text) {
  const out = {};
  for (const line of String(text || "").split("\n")) {
    const m = /^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)\s*$/.exec(line);
    if (!m) continue;
    let v = m[2].trim();
    if (
      (v.startsWith('"') && v.endsWith('"') && v.length >= 2) ||
      (v.startsWith("'") && v.endsWith("'") && v.length >= 2)
    ) {
      v = v.slice(1, -1);
    }
    out[m[1]] = v;
  }
  return out;
}

/** Read `.env.local` if it exists, merged under the real environment. */
export function loadEnvLocal() {
  const fromFile = fs.existsSync(ENV_PATH)
    ? parseEnv(fs.readFileSync(ENV_PATH, "utf8"))
    : {};
  return { ...fromFile, ...process.env };
}

/* Is this URL the local stack? One implementation, in server/localUrl.js, because
 * server/feed/index.js guards the recorded fixture with the same question. Re-exported
 * here so every script that already imports it keeps working. */
export { isLocalUrl };

/** Exit rather than proceed against anything that is not the local stack. */
export function assertLocal(url, what) {
  if (isLocalUrl(url)) return;
  console.error(
    "\n  REFUSING: " + what + " is a local-development-only operation, and\n" +
    "  SUPABASE_URL is " + (url ? "<" + url + ">" : "not set") + ".\n\n" +
    "  It only ever runs against the stack started by `npx supabase start`\n" +
    "  (http://127.0.0.1:54321). Nothing here is safe to point at a real database.\n"
  );
  process.exit(1);
}
